### ISSUE TITLE
Crawler failed, because of ValueError.

### ISSUE THREAD

**Issue by hydai** [henryyang42/NTHU_Course#109]
```
Crawling course for 105|10
Traceback (most recent call last):                                                                                                                           |
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.venv/tmp/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/root/.venv/tmp/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.venv/tmp/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.venv/tmp/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/root/git/test/NTHU_Course/crawler/management/commands/crawl_course.py", line 42, in handle
    crawl_course(ACIXSTORE, auth_num, cou_codes, ys)
  File "/root/git/test/NTHU_Course/crawler/crawler.py", line 111, in crawl_course
    handle_curriculum_html(response.text, cou_code)
  File "/root/git/test/NTHU_Course/crawler/crawler.py", line 95, in handle_curriculum_html
    collect_class_info(tr, cou_code_stripped)
  File "/root/git/test/NTHU_Course/crawler/crawler.py", line 71, in collect_class_info
    course_dict = course_from_tr(tr)
  File "/root/git/test/NTHU_Course/crawler/course.py", line 126, in course_from_tr
    part['size_limit'], part['fr'] = get_slfr(extract_text(tds[6]))
  File "/root/git/test/NTHU_Course/crawler/course.py", line 75, in get_slfr
    sl = int(sl)
ValueError: invalid literal for int() with base 10: '25新生保留25人'
```

**Comment by hydai** [comment]
cc @afg984

**Comment by afq984** [comment]
Is this still the case?

**Comment by henryyang42** [comment]
https://github.com/henryyang42/NTHU_Course/blob/upgrade_py3_django110/crawler/course.py#L72
Could be solved by changing ``大一新生保留`` to ``新生保留``.
And I don't know why.

**Comment by henryyang42** [comment]
```
10510CHEM345002
Traceback (most recent call last):                                                                                     |
  File "/Users/henryyang/Desktop/NTHU_Course/crawler/crawler.py", line 51, in save_syllabus
    course_dict = course_from_syllabus(html)
  File "/Users/henryyang/Desktop/NTHU_Course/crawler/course.py", line 161, in course_from_syllabus
    document = lxml.html.fromstring(html)
  File "/Users/henryyang/Desktop/NC/lib/python3.5/site-packages/lxml/html/__init__.py", line 867, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henryyang/Desktop/NC/lib/python3.5/site-packages/lxml/html/__init__.py", line 752, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77737)
  File "src/lxml/parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116674)
  File "src/lxml/parser.pxi", line 1711, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115220)
  File "src/lxml/parser.pxi", line 1051, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:109345)
  File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
  File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104323)
  File "<string>", line None
lxml.etree.XMLSyntaxError: line 43: b'Attribute colspan redefined'
```
And new error occurred...

**Comment by henryyang42** [comment]
No longer the case in #111
