### ISSUE TITLE
the course crawler is not working

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#77]
I will look into it when I have time

**Comment by hydai** [comment]
What's wrong?
It works on the deployed machine.

**Comment by afq984** [comment]
branch dev

**Comment by afq984** [comment]
``` python-traceback
Traceback (most recent call last):
  File "/home/afg/projects/NTHU_Course/crawler/crawler.py", line 62, in save_syllabus
    course.save()
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _save_table
    forced_update)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/base.py", line 723, in _do_update
    return filtered._update(values) > 0
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in execute_sql
    sql, params = self.as_sql()
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 969, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 627, in get_db_prep_save
    prepared=False)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 619, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/afg/projects/NTHU_Course/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1601, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

10410YZ  000102
```

it happens when a course is removed
